include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    always_specify_types: false
    annotate_overrides: true
    avoid_annotating_with_dynamic: true
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_print: true
    avoid_returning_null_for_future: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    cascade_invocations: true
    constant_identifier_names: false
    curly_braces_in_flow_control_structures: true
    depend_on_referenced_packages: true
    directives_ordering: true
    empty_catches: false
    file_names: true
    flutter_style_todos: true
    no_duplicate_case_values: true
    non_constant_identifier_names: false
    omit_local_variable_types: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_typing_uninitialized_variables: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    type_annotate_public_apis: true
    unnecessary_brace_in_string_interps: true
    unnecessary_this: true
    use_full_hex_values_for_flutter_colors: true
    use_key_in_widget_constructors: true
