name: qissat_hirfati
description: "A new Flutter project."
publish_to: 'none' 

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  connectivity_plus: ^6.1.4
  ios_smooth_page_indicator: ^1.1.5
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  file_picker: ^10.1.9
  url_launcher: ^6.3.1
  intl: ^0.20.2
  flutter_svg: ^2.1.0
  smooth_page_indicator: ^1.2.1
  
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  intl_utils: ^2.8.10
  build_runner: ^2.4.15

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/gif/
    - assets/animations/lottie/
    - assets/icons/icon/
    - assets/icons/svg/
    - assets/icons/app_icons/android/
    - assets/icons/app_icons/ios/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/ar/Rubik/Rubik-VariableFont_wght.ttf
        - asset: assets/fonts/ar/Rubik/Rubik-Italic-VariableFont_wght.ttf
          style: italic
        - asset: assets/fonts/ar/Rubik/static/Rubik-Black.ttf
          weight: 900
        - asset: assets/fonts/ar/Rubik/static/Rubik-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/ar/Rubik/static/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/ar/Rubik/static/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/ar/Rubik/static/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/ar/Rubik/static/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic